# Generated by Django 3.0.7 on 2020-06-18 17:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('yeapph', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='titletext',
            field=models.CharField(default=django.utils.timezone.now, max_length=90),
            preserve_default=False,
        ),
    ]
